name = "JulGameEditor"
uuid = "9cd31ca0-29e7-4e0e-a29b-ce588029d569"
authors = ["Kyjor <kyjordev@gmail.com>"]
repo = "https://github.com/Kyjor/JulGame.jl.git"
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
JulGame = "4850f9bb-d191-4a1e-9f97-ee64062927c3"

[compat]
JSON3 = "1"
SimpleDirectMediaLayer = "0.5"
CImGui = "~2.0"
julia = "1.9"